### ISSUE TITLE
Error: Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by aakilfernandes** [ethereumjs/ethereumjs-monorepo#114] opened 2016-12-29 23:14 UTC
Getting this while running the tests on a fresh clone.

OSX Yosemite
Node v6.3.0

```
# [bcInvalidRLPTest] BLOCK_gasLimit_TooLarge
ok 186 correct pre stateRoot
/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
              ^

Error: Number can only safely store up to 53 bits
    at assert (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/bn.js/lib/bn.js:506:7)
    at Object.exports.bufferToInt (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/ethereumjs-block/node_modules/ethereumjs-util/index.js:199:40)
    at BlockHeader.validateGasLimit (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/ethereumjs-block/header.js:146:26)
    at /Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/ethereumjs-block/header.js:196:15
    at /Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/ethereumjs-blockchain/index.js:326:7
    at /Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/levelup/lib/levelup.js:230:7
    at Immediate.callNext (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/memdown/memdown.js:173:5)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
npm ERR! Test failed.  See above for more details.
```

**Comment by DevNebulae** [comment] 2017-06-08 18:00
Getting the same error with no clue on how to fix it. Does anybody have a fix for this or an explanation as to why this happens?

**Comment by assafmo** [comment] 2017-06-29 18:58
This happened to me when I tried to index `string` type in an event.  
https://ethereum.stackexchange.com/a/7170/12112

**Comment by DevNebulae** [comment] 2017-07-01 09:42
I actually figured it out and it is REALLY stupid... It occurred to me when I actually used a value for the `gas` field which is greater than 53 bits. I actually set it to half an Ether and that works out to be greater than 53 bits...

**Comment by axic** [comment] 2017-12-09 20:36
This actually seems to be a bug in ethereumjs-block.

**Comment by hugo-dc** [comment] 2017-12-15 22:09
@axic recently I submitted a new PR to the tests repository, the tests I submitted is related to this problem.

https://github.com/ethereum/tests/pull/381

I think this is something that the bn.js library validates, here is an example of the validation in the iaddn function

https://github.com/indutny/bn.js/blob/master/lib/bn.js#L2145

**Comment by axic** [comment] 2017-12-17 21:58
This seems to be a problem in `ethereumjs-block` and that the block gas limit is higher than 53bits:
```
Error: Number can only safely store up to 53 bits
    at assert (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/bn.js/lib/bn.js:506:7)
    at Object.exports.bufferToInt (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/ethereumjs-block/node_modules/ethereumjs-util/index.js:199:40)
    at BlockHeader.validateGasLimit (/Users/aakilfernandes/projects/safemarket/ethereumjs-vm/node_modules/ethereumjs-block/header.js:146:26)
```

**Comment by riordant** [comment] 2017-12-20 18:21
having the same problem where gasLimit in testrpc is set greater than 9007199254740991 (2^53 -1) and tests are ran.

**Comment by greggootz** [comment] 2018-02-24 14:41
Make sure your `{gas: xxxx}` is a round number.

Bad: {gas: 40000.0000001}
Good: {gas: 40000}

`Math.floor()` to the rescue.

Example of usage:

`const estGas = Math.floor(await instance.myMethod.estimateGas({ from: wallet })`

Good luck!

**Comment by Shrugs** [comment] 2018-04-08 17:09
(sorry for the notification, but this is for future searchers)

I got this issue when I attempted to issue a `evm_increaseTime` call against ganache while using a duration argument that was stupidly large. It was hard to track down because I was accidentally using a BigNumber in a traditional `30 + myBigNumber` way.

**Comment by liamzebedee** [comment] 2018-10-09 14:09
Just encountered this. Not relevant exactly the JS VM, but for any other souls that come here, an addition to what @DevNebulae said:

I had set the gasLimit with ganache-cli to a number bigger than 53 bits. Changed it, still didn't work. Turns out that Metamask caches the gas limit, so you have to switch between networks and switch back before it gets the new one. Until then, you'll get a 53 bits error on any transaction.

**Comment by nikita-fuchs** [comment] 2018-11-05 14:21
My gaslimit is 800000 and I still get this error. Here is the code that causes it: 

_BN.js:498_
```
BN.prototype.toNumber = function toNumber () {
    var ret = this.words[0];
    if (this.length === 2) {
      ret += this.words[1] * 0x4000000;
    } else if (this.length === 3 && this.words[2] === 0x01) {
      // NOTE: at this stage it is known that the top bit is set
      ret += 0x10000000000000 + (this.words[1] * 0x4000000);
    } else if (this.length > 2) {
      assert(false, 'Number can only safely store up to 53 bits');
    }
    return (this.negative !== 0) ? -ret : ret;
  };
```
Does anyone have a clue what he is parsing here?

**Comment by holgerd77** [comment] 2018-11-05 20:21
@nikita-fuchs You should be able to debug this by directly injecting some log statements in this file in your ``node_modules`` folder?

**Comment by nikita-fuchs** [comment] 2018-11-05 20:55
Not indexing a string as event parameter solved this for me. It's often
said this wouldn't be possible anyway, but as the compiler won't complain,
it seems it's only the JS libraries are having problems with that?

Am Mo., 5. Nov. 2018, 21:21 hat Holger Drewes <notifications@github.com>
geschrieben:

**Comment by orlein** [comment] 2019-01-18 10:01
Hello, I'm facing the same issue.

You can just get web3's util to variable. for example,
```javascript
var BigNumber = web3.utils.BN;
var amount = new BigNumber(3700 * 10 ** 3);
```
and amount is BigNumber. so you can compare to any Ethereum uint256 like this:

```javascript
return Token.deployed().then((instance) => {
    token = instance;
    return token .balanceOf.call(account_one);
}).then((balance) => {
    account_one_starting_balance = balance;
    return token.balanceOf.call(account_two);
}).then((balance) => {
    account_two_starting_balance = balance;
    return token.transfer(account_two, amount, {from: account_one});
}).then(() => {
    return token.balanceOf.call(account_one)
}).then((balance) => {
    account_one_ending_balance = balance;
    return token.balanceOf.call(account_two);
}).then((balance) => {
    account_two_ending_balance = balance;
    assert.equal(account_one_ending_balance.toString(), account_one_starting_balance.sub(amount).toString(), "Amount wasn't correctly taken from the sender");
    assert.equal(account_two_ending_balance.toString(), account_two_starting_balance.add(amount).toString(), "Amount wasn't correctly sent to the receiver");
});
```
This code is from truffle's contract test code to test if the transfer is working with account_one to account_to.

**Comment by holgerd77** [comment] 2019-04-30 15:15
There are actually few issues which make me so confused within the whole ``EthereumJS`` org like this one. Open since 2016, with new reports coming in several times, all citing very much different code parts.

Is this still a thing? How much is this related to the VM implementation? Does anyone have some code part which can directly be executed on the VM and is triggering the respective error?

**Comment by macman18** [comment] 2019-05-21 16:03
How I have seen in several blogs: the best solution is downgrade the truffle version to truffle@4.1.5. The problem is related to quorum in truffle version 5. I have made this downgrading and now everything works!

**Comment by alcuadrado** [comment] 2019-05-21 20:12
Can you give us more info about your failing setup @macman18? Truffle version? Node version? Are you using ganache? Which version? Thanks!

**Comment by macman18** [comment] 2019-05-21 20:23
> Can you give us more info about your failing setup @macman18? Truffle version? Node version? Are you using ganache? Which version? Thanks!

Of course. I've also added a new discovered... Now it is definitive!

**Comment by alcuadrado** [comment] 2019-05-21 21:18
> This has not been so for me. I have continue to use truffle v5. I've resolved by checking my gas limit when I sent a transaction.
> gasLimit: web3.utils.toHex( gas_limit ),//The maximum gas provided for this transaction (gas limit)

So the problem appeared when sending a tx without an explicit gas limit? What is the value of `gas_limit`? Can you paste the entire statement that sends that tx?

**Comment by macman18** [comment] 2019-05-21 21:31
> So the problem appeared when sending a tx without an explicit gas limit? What is the value of `gas_limit`? Can you paste the entire statement that sends that tx?
> In my case, also, I had to control whether  transaction gas were less or equal of the ganache gas limit. You have to check it because could be different and the transaction one could be higher.
> Also, your truffle config would be useful.

My versions:
Node: v8.11.4
Truffle: 5.0.12
Web3: 1.0.0-beta.52
Truffle-contract: 4.0.11
Truffle-interface-adapter@0.1.2
│ └── web3@1.0.0-beta.37
└── web3@1.0.0-beta.37
Ganache-cli: v6.4.3 (ganache-core: 2.5.5)
Ethereumjs-tx: 1.3.4
================================================================================
Truffle-config.js

 networks: {
    // Useful for testing. The `development` name is special - truffle uses it by default
    // if it's defined here and no other network is specified at the command line.
    // You should run a client (like ganache-cli, geth or parity) in a separate terminal
    // tab if you use this network and you must also set the `host`, `port` and `network_id`
    // options below to some value.
    //
     development: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 8545,            // Standard Ethereum port (default: none)
      network_id: "*",       // Any network (default: none)
      //websockets: true 
     }
    // Another network with more advanced options...
    // advanced: {
      // port: 8777,             // Custom port
      // network_id: 1342,       // Custom network
      // gas: 8500000,           // Gas sent with each transaction (default: ~6700000)
      // gasPrice: 20000000000,  // 20 gwei (in wei) (default: 100 gwei)
      // from: <address>,        // Account to send txs from (default: accounts[0])
      // websockets: true        // Enable EventEmitter interface for web3 (default: false)
    // },

    // Useful for deploying to a public network.
    // NB: It's important to wrap the provider as a function.
    // ropsten: {
      // provider: () => new HDWalletProvider(mnemonic, `https://ropsten.infura.io/${infuraKey}`),
      // network_id: 3,       // Ropsten's id
      // gas: 5500000,        // Ropsten has a lower block limit than mainnet
      // confirmations: 2,    // # of confs to wait between deployments. (default: 0)
      // timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
      // skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    // },

    // Useful for private networks
    // private: {
      // provider: () => new HDWalletProvider(mnemonic, `https://network.io`),
      // network_id: 2111,   // This network is yours, in the cloud.
      // production: true    // Treats this network as if it was a public net. (default: false)
    // }
  },

  // Set default mocha options here, use special reporters etc.
  mocha: {
    // timeout: 100000
  },

  // Configure your compilers
  compilers: {
    solc: {
      version: "0.5.7"    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    }//solc
  }
}

**Comment by Chococoin** [comment] 2019-06-18 10:30
## My Versions:
Truffle v5.0.22,
Node v10.15.2,
Ganache CLI v6.4.4 (ganache-core: 2.5.6)

## a portion of my code:

```
219.-  it('Receiving properly a bid', async () => {
220.-      var newBid = 5 * Math.pow(10, 18);
221.-      bid = await chocoAuction.bid({ from: accounts[1], value: newBid });
222.-      highestBid = await chocoAuction.highestBid.call({ from: accounts[2] });
*223.-      var hiBid = highestBid.toNumber();
224.-      console.log(bid);
225.-      assert(bid);
 	  ;})
```
# The Error after $> truffle test:

`    'Receiving properly a bid:'
     Error: Number can only safely store up to 53 bits
      at assert (C:\Users\Choco\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bn.js\lib\bn.js:6:1)
      at BN.toNumber (C:\Users\Choco\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bn.js\lib\bn.js:506:1)
      at Context.it (test\chocoAuction.js:223:28)
      at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by trongdth** [comment] 2020-10-06 07:46
I can able to run truffle test by using `toString()` method. Here is an example of getting token balance

```javascript
const o = {
				balance: 2000000000 * (10 ** 18),

			}

			let owner_balance = await tokoin.balanceOf(root, {
				from: root
			});

			eq(o.balance, owner_balance.toString())
```

**Comment by holgerd77** [comment] 2021-06-11 11:34
This hasn't been reported for quite some time, will close.

**Closed by holgerd77** 2021-06-11 11:34 UTC
Labels: eval: needs validation, package: vm, prio: P3 important, type: bug

**Comment by holgerd77** [comment] 2021-06-11 11:36
(feel free to reopen though)

**Comment by holgerd77** [comment] 2021-06-11 11:59
On the various libraries, input is now directly taken as a `Buffer` or a `BN.js` object - at least for the values allowing for a bigger number input. And internally `number` conversion is generally avoided. So it is generally very likely that this shouldn't be an issue any more.
