### ISSUE TITLE
Issues correctly importing

### ISSUE THREAD

**Issue by rsmith2002** [ethereumjs/ethereumjs-monorepo#1614] opened 2021-12-16 15:15 UTC
Hey, sorry for raising another issue its the easiest way for me to directly find a solution compared to the outdated stackoverflow answers I keep seeing. I am trying to install transaction so that: 
ReferenceError: Transaction is not defined 
doesnt happen for:
const tx = Transaction.fromTxData(rawTransaction, { 'common': BSC_FORK })

the way I am doing now:
import { Transaction } from '@ethereumjs/tx'
doesnt seem to work and I have tried multiple combinations for this, I had a similar issue with importing common the other day 
Changing to import Tx from 'ethereumjs-tx'; and var transaction = new Tx(rawTransaction, { 'common': BSC_FORK }); states tx is not a constructor

so if there is somewhere I should be looking please let me know 😃

**Comment by acolytec3** [comment] 2021-12-17 00:53
Are you using typescript or vanilla JavaScript? From the little bit you shared, if using typescript, it should work.

If you have an example repo that reproduces the issue, I can dig into it

**Comment by rsmith2002** [comment] 2021-12-17 01:38
> Are you using typescript or vanilla JavaScript? From the little bit you shared, if using typescript, it should work.
> 
> If you have an example repo that reproduces the issue, I can dig into it

As far as I'm aware it's vanilla ish JavaScript using node.js. The example I was basing it off  was stackoverflow.com/questions/67341080/i-am-trying-to-execute-a-swap-on-pancakeswap-using-web3-but-i-get-an-error-when

**Comment by rsmith2002** [comment] 2021-12-17 12:05
> If you're using NodeJS and javascript, try replacing the import statement with 
> `const Transaction = require('@ethereumjs/tx').Transaction`
> 
> That seems to work fine for me in a simple script like this:
> 
> ```js
> const Transaction = require('@ethereumjs/tx').Transaction
> 
> const tx = Transaction.fromTxData({})
> 
> console.log(tx)
> ```

Suppose that should work, for some reason I keep getting ' X.js is an ES module file ... Who's nearesr package.json contains type:module....' but type module has been deleted and it keeps hinting to use import instead so I'm not sure if that solution will work

**Comment by acolytec3** [comment] 2021-12-17 13:10
Can you push a repo to GitHub that reproduces your setup so we can triage further? Our modules are not compiled as ES modules so that error doesn't make a lot of sense to me.

**Comment by rsmith2002** [comment] 2021-12-17 15:46
> Can you push a repo to GitHub that reproduces your setup so we can triage further? Our modules are not compiled as ES modules so that error doesn't make a lot of sense to me.

yea sure Ill just post the package.json and .js here to make it easier. High chance I just have messed something up with the environment
https://pastebin.com/ary726Vz

**Comment by acolytec3** [comment] 2021-12-17 16:20
I see that `chalk` is throwing that ESM error when I try to run your code.  I commented out that piece and the `Transaction.fromTxData` part works fine. I'm not 100% sure how to solve the `chalk` ESM error but if you need it, you can probably do something like `const chalk = await import('chalk')` or something though you'll have to put everything else inside a `.then...` statement to do so.

**Comment by rsmith2002** [comment] 2021-12-17 16:26
> I see that `chalk` is throwing that ESM error when I try to run your code. I commented out that piece and the `Transaction.fromTxData` part works fine. I'm not 100% sure how to solve the `chalk` ESM error but if you need it, you can probably do something like `const chalk = await import('chalk')` or something though you'll have to put everything else inside a `.then...` statement to do so.
That is weird yea I got rid of the chalk which wasn't an error before and it seems to be working just fine now, thanks for sorting that. I noticed that it isn't actually transacting anything though, nothing is coming up on bscscan under my address. As of your knowledge is that code actually... doing a transaction?

**Comment by acolytec3** [comment] 2021-12-17 19:05
It looks like it should be.

**Comment by rsmith2002** [comment] 2021-12-17 19:13
> It looks like it should be.

Looks like it but isn't I dont think

**Comment by rsmith2002** [comment] 2021-12-19 21:21
Any clue?

**Comment by acolytec3** [comment] 2021-12-19 22:49
Sorry, that code is kind of messy and `web3js` isn't my strong suite.   Based on skimming it, it generally looks like it might work but I have no knowledge of the specific contract being invoked.  The one thing that definitely looks odd is line 134 where you're instantiating the private key.  That `Buffer.from('privkey','hex')` is creating a buffer from the string `privkey`, not an actual private key.  Anything else you should probably take to stackoverflow.  I don't see any obvious issues in the sections where you're using our code.

**Comment by rsmith2002** [comment] 2021-12-19 23:19
> Sorry, that code is kind of messy and `web3js` isn't my strong suite.   Based on skimming it, it generally looks like it might work but I have no knowledge of the specific contract being invoked.  The one thing that definitely looks odd is line 134 where you're instantiating the private key.  That `Buffer.from('privkey','hex')` is creating a buffer from the string `privkey`, not an actual private key.  Anything else you should probably take to stackoverflow.  I don't see any obvious issues in the sections where you're using our code. 

Yea the code is quite scuffed and pieced together. Thanks I'll take a look into it

**Comment by evertonfraga** [comment] 2021-12-20 23:16
@rsmith2002 for simplicity, it might be worth trying `ts-node` to run the initial code with `import`. 

https://github.com/TypeStrong/ts-node

**Comment by gabrocheleau** [comment] 2022-01-05 22:50
Closing this as suggested by @rsmith2002 . Feel free to re-open should it be required.

**Closed by gabrocheleau** 2022-01-05 22:50 UTC
Labels: package: tx
