### ISSUE TITLE
Zhejiang empty withdrawals EthereumJS client encoding issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2528] opened 2023-02-10 13:51 UTC
On the [Zhejiang](https://zhejiang.ethpandaops.io/) testnet seems to be malformed/wrongly encoded blocks sent by the EthereumJS client in the case that there are no withdrawals associated with a block, see [this](https://discord.com/channels/595666850260713488/1073208138309840926) Eth R&D Discord thread and an associated issue https://github.com/ethereum/go-ethereum/issues/26647 opened on the go-ethereum side.

If I replicate the core of the issue correctly, I think we create blocks at some point where the withdrawals root in the block is correctly being set to the empty trie root but the withdrawals field is decoded (by the other-side-client) as `undefined` or empty instead of an empty list `[]`, which would be the correct structure to use.

Therefore such a block is reported as invalid by e.g. Geth while originally this was a valid block.

I followed some encoding paths already but couldn't imminently find some weak spots, following places to look at:

- Block encoding preparation with `raw()` and then `serialize()` in the Block package
- Eventually some initialization path in the Block library along the static constructors (unlikely though I would say)
- Maybe it's a thing in combination with a wrong Common, unlikely as well if the withdrawals root is present I would say?
- Also a place to look: the block builder in the VM or the outer block building code in the Client package
- And finally: devp2p encoding of block structures in the Client

Happy debugging, I will also continue to try things out! 🧑🏽‍💻

**Comment by g11tech** [comment] 2023-02-10 17:45
t shouldn't be the issue: since the code flow is: 

```typescript
try {
      body = await this.getBody(hash, number)
    } catch (error: any) {
      if (error.code !== 'LEVEL_NOT_FOUND') {
        throw error
      }
      // If this block had empty withdrawals push an empty array in body
      if (header.withdrawalsRoot !== undefined && header.withdrawalsRoot.equals(KECCAK256_RLP)) {
        body.push([])
      }
    }
```
i.e. if no bodies has been pushed (hats when it will error and come to this catch), then it could be the scenario of empty transactions and empty withdrawals which is why we push []

if there was something in the body, then body would have just been assigned from getBody

**Comment by holgerd77** [comment] 2023-02-13 09:40
> t shouldn't be the issue: since the code flow is:
> 
> ```ts
> try {
>       body = await this.getBody(hash, number)
>     } catch (error: any) {
>       if (error.code !== 'LEVEL_NOT_FOUND') {
>         throw error
>       }
>       // If this block had empty withdrawals push an empty array in body
>       if (header.withdrawalsRoot !== undefined && header.withdrawalsRoot.equals(KECCAK256_RLP)) {
>         body.push([])
>       }
>     }
> ```
> 
> i.e. if no bodies has been pushed (hats when it will error and come to this catch), then it could be the scenario of empty transactions and empty withdrawals which is why we push []
> 
> if there was something in the body, then body would have just been assigned from getBody

Can we nevertheless include a check here if `body.length === 2` before we push the empty array? Otherwise we can theoretically end up here with an empty array for withdrawals already included and then there is another out-of-semantics array pushed on top of that. Might be that code procedural internals do not allow for this case to happen, I would nevertheless feel safer with this additional check.

**Comment by holgerd77** [comment] 2023-02-13 10:40
> > t shouldn't be the issue: since the code flow is:
> > ```ts
> > try {
> >       body = await this.getBody(hash, number)
> >     } catch (error: any) {
> >       if (error.code !== 'LEVEL_NOT_FOUND') {
> >         throw error
> >       }
> >       // If this block had empty withdrawals push an empty array in body
> >       if (header.withdrawalsRoot !== undefined && header.withdrawalsRoot.equals(KECCAK256_RLP)) {
> >         body.push([])
> >       }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i.e. if no bodies has been pushed (hats when it will error and come to this catch), then it could be the scenario of empty transactions and empty withdrawals which is why we push []
> > if there was something in the body, then body would have just been assigned from getBody
> 
> Can we nevertheless include a check here if `body.length === 2` before we push the empty array? Otherwise we can theoretically end up here with an empty array for withdrawals already included and then there is another out-of-semantics array pushed on top of that. Might be that code procedural internals do not allow for this case to happen, I would nevertheless feel safer with this additional check.

Update: ah, didn't see that this is happening in the `catch` clause, please disregard.

**Comment by g11tech** [comment] 2023-02-17 11:29
closing as confirmed by Marius that ethereumjs didn;t give malformed blocks with more validations added in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2534

**Closed by g11tech** 2023-02-17 11:29 UTC
Labels: type: bug, eval: needs validation, package: client
