### ISSUE TITLE
Error: Expected Uint8Array [Object of Buffer Given!!!]

### ISSUE THREAD

**Issue by shahradelahi** [ethereumjs/ethereumjs-monorepo#2374] opened 2022-10-19 17:33 UTC
Error message and stack
```
Error: Expected Uint8Array

    at bytesToHex (---\node_modules\@noble\secp256k1\lib\index.js:498:15)
    at bytesToNumber (---\node_modules\@noble\secp256k1\lib\index.js:541:24)
    at normalizePrivateKey (---\node_modules\@noble\secp256k1\lib\index.js:747:15)
    at initSigArgs (---\node_modules\@noble\secp256k1\lib\index.js:826:15)
    at signSync (---\node_modules\@noble\secp256k1\lib\index.js:861:28)
    at ecsign (---\node_modules\@ethereumjs\util\src\signature.ts:21:41)
    at Transaction.sign (---\node_modules\@ethereumjs\tx\src\baseTransaction.ts:332:31)
    at Object.sign (---\lib\__tests__\issue.ts:27:27)
    at Promise.then.completed (---\node_modules\jest-circus\build\utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (-\jest-circus\build\utils.js:259:10)
    at _callCircusTest (---\node_modules\jest-circus\build\run.js:277:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _runTest (---\node_modules\jest-circus\build\run.js:209:3)
    at _runTestsForDescribeBlock (---\node_modules\jest-circus\build\run.js:97:9)
    at _runTestsForDescribeBlock (---\node_modules\jest-circus\build\run.js:91:9)
    at run (---\node_modules\jest-circus\build\run.js:31:3)
    at runAndTransformResultsToJestFormat (---\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:135:21)
    at jestAdapter (---\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:92:19)
    at runTestInternal (---\node_modules\jest-runner\build\runTest.js:411:16)
    at runTest (---\node_modules\jest-runner\build\runTest.js:499:34)

```

Source Code:
```
import {describe, test} from "@jest/globals";
import {Transaction} from '@ethereumjs/tx'
import {Chain, Common, Hardfork} from '@ethereumjs/common'

describe('testsuite', () => {

   test('test', () => {

      const txParams = {
         nonce: '0x00',
         gasPrice: '0x09184e72a000',
         gasLimit: '0x2710',
         to: '0x0000000000000000000000000000000000000000',
         value: '0x00',
         data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
      };

      const common = new Common({chain: Chain.Mainnet, hardfork: Hardfork.Istanbul});
      const tx = Transaction.fromTxData(txParams, {common});

      const privateKey = Buffer.from(
          'e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109',
          'hex'
      );

      const signedTx = tx.sign(privateKey);
      const serializedTx = signedTx.serialize();

   });

});
```

Versions:
```json
{
   "jest": "28.1.0"
   "@ethereumjs/tx": "4.0.0"
}
```

**Comment by acolytec3** [comment] 2022-10-19 19:55
Are you trying to run this in browser?  I set up a local nodejs repo using jest and was able to run this script and it passed just fine.

**Comment by shahradelahi** [comment] 2022-10-20 07:13
No, I didn't run it on browser, and also I just created a repo, so you can check it
https://github.com/shahradelahi/ethereumjs-issue-2374

**Comment by acolytec3** [comment] 2022-10-22 00:24
I think the issue here is that you are indeed using a browser based app setup.  Your repo setup is using jest with `js-dom` which is a browser emulator framework for running tests.  If you refer to this repo - https://github.com/acolytec3/jest-ethjs and run the script with just `jest` running in NodeJS, the script passes.  The issue is that we use `buffer` internally throughout our code and requires a polyfill in order to run in the browser since the browser environment doesn't support `buffer`.  I don't know that much about NextJS and whether they support polyfills natively but here's an example repo that uses `create-react-app` with some hackery to get the `tx` library working in the browser.

**Comment by shahradelahi** [comment] 2022-10-22 05:57
Thanks for your help, It works now, I just removed the `testEnvironment: 'jsdom'` from jest config, and it works fine.
Honestly, I don't need this `jsdom` for my tests, I just used the official Next.js example for integration jest with Next.js.
I think that's better to add this to the documentation, because I think it's not clear for everyone.
Anyway, thanks for your help.

**Comment by acolytec3** [comment] 2022-10-24 15:05
Thanks!  Will close this for now.  We have a bigger to-do on our roadmap to provide more guidance for working with our libraries in browser.  Feel free to reopen if new things emerge.

**Closed by acolytec3** 2022-10-24 15:05 UTC
Labels: type: bug, type: discussion / question, eval: needs validation, eval: needs discussion, package: tx
