### ISSUE TITLE
VM: Create collisions using runCode() and runCall()

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-monorepo#613] opened 2019-11-08 18:15 UTC
I'm not completely sure if this should be considered a bug because I don't understand what the intended use case of `runCode` and `runCall` methods is, but using them can lead to unexpected `CREATE_COLLISION` errors. 

This can be reproduced like this:

1. Instantiate a VM
2. Add an `Account` with some ETH.
3. Deploy a contract with that account by sending a TX to the null address.
4. Use `runCall` to simulate a call to the null address.

`runCall` will try to deploy the contract, and fail. This is because contract addresses are computed using the caller and their nonce. In this case, the caller is the account that we created, and the nonce is always 0 for `runCall` and `runCode`. But we already deployed a contract from the 0-nonce TX of that account, so an address clash happens.

This is a corner case that I found right before shipping Buidler EVM 😅 I was using `runCall` in our [`eth_call` RPC](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_call)  implementation and started seeing `CREATE_COLLISION` errors when testing with real codebases. It may seem weird to run a deployment with `eth_call`, but some projects do it to get revert reasons from failed txs.

My solution was to use use a `FakeTransaction` and `runTx`, and revert any state change. I guess that's why `FakeTransaction` was created in the first place. I really wanted to remove it when migrating `-tx` to TS, but I'm happy I didn't :)

Should we add `nonce` to `RunCodeOpts` and `RunCallOpts`?

**Comment by s1na** [comment] 2019-11-11 10:29
Geez, that's some corner case :)

> Should we add nonce to RunCodeOpts and RunCallOpts?

That seems like a fair solution to me.

**Comment by atkinsonholly** [comment] 2019-12-18 16:24
@alcuadrado I'll take a look

**Comment by alcuadrado** [comment] 2019-12-18 16:37
Feel free to ask any questions. I think the hardest part of this would be deciding where and how to test these changes.

**Comment by jochem-brouwer** [comment] 2020-06-29 18:40
We should absolutely add a nonce to `RunCodeOpts` and `RunCallOpts`. This is a bit more complex than just passing nonce along the messages; it looks like `evm` reads this from the State instead of reading it from the message call.

I think a related issue here is #799, we might want to merge these two issues into a single PR?

**Comment by jochem-brouwer** [comment] 2020-06-29 22:49
Heya, I thought implementing nonce in `RunCodeOpts` would make sense, but actually it does not.

The reason is that `RunCode` calls the interpreter. The interpreter does not care if we are a normal message call or a create message. If it is a create message, this is called from `evm.ts` in `_executeCreate`: if the interpreter does not error it will dump the return value of the interpreted code into the contract. It thus makes no sense if we add nonces to `runCode`.

However, iff `runCode` would invoke a `CREATE` opcode, then this will call into `EEI` and back into the `EVM` which calls into `executeMessage` which will then (as per `runCall`) invoke `_executeCreate`.

I conclude that it makes no sense to include nonces in `RunCodeOpts`.

**Comment by jochem-brouwer** [comment] 2020-07-01 17:02
Adding this nonce option temporarily changes the nonces of the calling account, runs the call, and then changes it back to the original value. This could lead to undesired (?) side effects where the balance of the account is changed (i.e. besides deducting gas costs the code could also send some ETH over to the sender). I therefore do not know if we want to implement this feature. 

@alcuadrado isn't it better to use `runTx` in this case? Can't you use that instead of using `runCall`? 

Thoughts? @holgerd77 @s1na @ryanio @evertonfraga

**Comment by alcuadrado** [comment] 2020-07-01 17:14
> @alcuadrado isn't it better to use `runTx` in this case? Can't you use that instead of using `runCall`?

Yes, that's actually what I'm doing. I checked ganache's code, and they do the same.

**Comment by holgerd77** [comment] 2021-06-11 12:09
What to do with this issue? Close? Or are there still some design adoption considerations to be drawn from here (didn't re-read to closely TBH)?

**Comment by ryanio** [comment] 2021-06-11 22:03
just catching up, so @alcuadrado you solved your issue here by moving to `runTx`?

is anyone actually using `runCodd

**Comment by alcuadrado** [comment] 2021-06-12 00:46
Yeah, it was solved by moving to runTx. 

I don't think `runCall` has any valid use case tbh. Maybe `runCode` doesn't have one either? `runCall` seems to do something that it doesn't, and it's confusing.

**Comment by holgerd77** [comment] 2021-06-14 10:23
I think `runCode` does have its use cases with just running the plain bytecode sequences with not bothering about setting the outer framing with artificially set up a tx or something, see e.g. our [usage](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm#usage) example in the README, we also use this in various places of the tests.

We might want to consider to deprecate `runCall` though as being part of the API for v6? Thoughts? 🤔

**Comment by alcuadrado** [comment] 2021-06-15 21:28
I think that'd make sense.

I agree with the `runCode` use case.

**Comment by gabrocheleau** [comment] 2023-07-06 13:14
@jochem-brouwer Just stumbled into this old issue which seems related to the discussions in #2861

**Comment by holgerd77** [comment] 2024-10-09 10:21
Hi @jochem-brouwer, can you please take (short-term) responsibility of this issue? Closing is definitely an option. If you have some alternative suggestion for an implementation please open a new issue with an evolved and concrete proposal and close this issue. Thanks! 🙏

**Comment by jochem-brouwer** [comment] 2024-10-09 11:00
Thanks for the ping @holgerd77, took a look, this is the intended behavior. 

The EVM is supposed to runCall / runCode on top of some state (which is identified by the state root). Therefore, if you try to first run a call (which creates a contract), and then run the call **again** (but now on the "new state"), this indeed creates an address clash, but ONLY if the original sender was supposed to be an EOA. In our `runTx` (which handles EOA calls) there actually is some extra logic which changes the state (in this case, it bumps the nonce of the EOA!). However, if you thus "simulate this EOA call" in the EVM, the sender nonce is not bumped. Therefore, if you run the same transaction, the EVM will see the same nonce and therefore try to deploy it at the same address.

There are two simple ways to get around this:

- The clean one: use `runTx` from VM to correctly simulate transactions
- The dirty one: bump the nonce after `runCall` in EVM. This will not correctly simulate EOA calls, because it skips some state-changing logic in `runTx`, such as charging the tx base cost (21000 in most cases), charging for access lists, etc.

Will close.

**Closed by jochem-brouwer** 2024-10-09 11:00 UTC
Labels: effort: E1 hours, package: vm

**Comment by holgerd77** [comment] 2024-10-09 11:36
@jochem-brouwer Thanks for having a look and the detailed "closing-analysis"! 🙏 👍
