### ISSUE TITLE
Code size error when actual failure reason is OOG

### ISSUE THREAD

**Issue by davidmurdoch** [ethereumjs/ethereumjs-monorepo#2664] opened 2023-04-25 16:39 UTC
https://github.com/ethereumjs/ethereumjs-monorepo/blob/49c2d93b94e70887d4fafff123eec19ef6a35fec/packages/evm/src/evm.ts#L584

**Comment by jochem-brouwer** [comment] 2023-04-25 16:43
I assume you want us to branch on:

1. If returned code size > max code size, report current error
2. Else, return OOG error

?

**Comment by davidmurdoch** [comment] 2023-04-25 16:45
I didn't mean to open this yet. I was using the github.dev editor and it opened it for me, I thought I'd have a chance to add more context first.

Context coming right up!

**Comment by davidmurdoch** [comment] 2023-04-25 16:54
[This issue](https://github.com/trufflesuite/ganache/issues/4361) came up recently when web3 was updating their tests to shanghai. The error returned by the EVM is that the code size is too great, but the gas used was the problem and their contract deployment actually doesn't have enough gas under shanghai.

I suspect they'll be many more users upgrading to shanghai that run into this erroneous error message over the next few months. So it'd be helpful to update the error messaging here soon.

(sorry again for that initial contextless issue!)

**Comment by jochem-brouwer** [comment] 2023-04-25 16:57
This is not related to Shanghai. This does the "deployed code size" check, *not* the "initcode size check" (EIP 3860). See EIP https://eips.ethereum.org/EIPS/eip-170

I agree we should change though.

**Comment by davidmurdoch** [comment] 2023-04-25 17:01
I think it is related to shanghai. Code that use to deploy successfully at a given gas limit no longer does because init code uses more gas now.

**Comment by jeffsmale90** [comment] 2023-04-25 23:04
I this this is a duplicate of this issue #2466 ?

**Comment by davidmurdoch** [comment] 2023-04-26 00:31
It is. Thanks @jeffsmale90! I leave it to @jochem-brouwer to close this one.

**Comment by jochem-brouwer** [comment] 2023-04-26 11:29
Yup, just assigned #2466 to me and will work on this soon.

**Closed by jochem-brouwer** 2023-04-26 11:29 UTC
